

export const safeAction = {
    CREATE_SAFE: 'CREATE_SAFE',
    UPDATE_SAFE: 'UPDATE_SAFE',
    DELETE_SAFE: 'DELETE_SAFE',
    CREATE_SECRET: 'CREATE_SECRET',
    DELETE_SECRET: 'DELETE_SECRET',
    SELECT_ID: 'SELECT_ID'
};